### ISSUE TITLE
v0.1.0 code-TODO checklist

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/colourvalues#18]
- [x] https://github.com/SymbolixAU/RcppViridis/blob/master/inst/include/RcppViridis/scale/scale.hpp#L24
- [x] https://github.com/SymbolixAU/RcppViridis/blob/master/tests/testthat/test-colour_values.R#L58
- [x] [`na_colour` rgb return](https://github.com/SymbolixAU/RcppViridis/blob/master/inst/include/RcppViridis/colours/colours_rgb.hpp#L50)
