### ISSUE TITLE
input data types

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/colourvalues#3]
Support all data types

---
## TODO
- [x] numeric (inc. NA, NaN, Inf, NA_integer_)
- [x] factor (inc. NA)
- [x] character (inc. NA_character_) (to sort, not not to sort?)
- [x] logical (inc. NA)
- [x] Date (inc. NA)
- [x] POSIX (inc. NA)

**Comment by tim-salabim** [comment]
I'd like to raise also NA handling & user supplied breaks (if better as a separate issue, let me know, I'll happily open one).

Otherwise a wicked idea to have very fast variable coloring. A first benchmark against my current implementation in [mapview](https://github.com/r-spatial/mapview/blob/develop/R/color.R#L184) (using `lattice::level.colors`) suggests a 100+ fold speedup!

**Comment by SymbolixAU** [comment]
@tim-salabim thanks for the reminder on `NA`s - I've added to the TODO. 
How do you think they should be handled - assigned a 'grey' like `#808080` ? 

Would you mind expanding what you mean by 'user supplied breaks'?

**Comment by tim-salabim** [comment]
An argument `na.color` would be ideal IMO. In mapview we use `#BEBEBE` as a default value. With breaks (in mapview we use argument `at` - again following `lattice` semantics) I mean that users may want to control the number of colors used. Here's an example:
```r
library(mapview)

df <- data.frame(a = 10, x = 1:250)
df$col <- mapview:::zcolColors(df$x, at = seq(0, 250, 50))
barplot(height = df$a, col = df$col, border = NA, space = 0)
```
![breaks](https://user-images.githubusercontent.com/2826432/45074492-f89e7880-b0e3-11e8-9810-56c054bc1713.png)

```r
df$col2 = mapview:::zcolColors(df$x, at = seq(1, 250, 50), na.color = "magenta")
barplot(height = df$a, col = df$col2, border = NA, space = 0)
```
![breaks_na](https://user-images.githubusercontent.com/2826432/45074504-05bb6780-b0e4-11e8-92b9-d5a818b53a27.png)

**Comment by SymbolixAU** [comment]
understood! thanks for the examples, and it's close to what I had in mind [here](https://github.com/SymbolixAU/RcppViridis/issues/1), only more thought-out and well defined!

**Comment by tim-salabim** [comment]
I just followed the well paved lattice path. No need to reinvent the wheel :-)

FWIW, if your implementation here turns out to produce similar outputs to the current mapview implementation (and if on CRAN at some stage) I am planning to utilise it in mapview as it fits perfectly with its scope. I am also very eager to use it in [leaflet.pixi](https://github.com/tim-salabim/leaflet.pixi) provided I ever get value coloring to work in the first place...

**Comment by SymbolixAU** [comment]
@tim-salabim I've created a 'discussion' issue #8  - could you move your last two comments there?

**Comment by SymbolixAU** [comment]
@tim-salabim [this commit](https://github.com/SymbolixAU/RcppViridis/commit/fe3a9ddce0f7fadb451eb62217869c4af0a20e50) should closely replicate the `mapview` implementation for numerics

```r
df <- data.frame(a = 10, x = 1:10)
df$col <- mapview:::zcolColors(df$x)
barplot(height = df$a, col = df$col, border = NA, space = 0)

df$col <- RcppViridis::colour_variables(df$x)
barplot(height = df$a, col = df$col, border = NA, space = 0)

df <- data.frame(a = 10, x = c(1:5,NA,7,NA,9,10))
df$col2 = mapview:::zcolColors(df$x, na.color = "#00FF00")
barplot(height = df$a, col = df$col2, border = NA, space = 0)

df$col2 <- RcppViridis::colour_variables(df$x, na_colour = "#00FF00")
barplot(height = df$a, col = df$col2, border = NA, space = 0)
```

**Comment by tim-salabim** [comment]
Yes, closely:
```r
> mapview:::zcolColors(df$x)
 [1] "#440154" "#482878" "#3E4A89" "#31688E" "#26828E" "#1F9E89" "#35B779" "#6DCD59" "#B4DE2C" "#FDE725"
> RcppViridis::colour_variables(df$x)
 [1] "#440154" "#482878" "#3E4A89" "#31688E" "#26838E" "#1F9D89" "#35B779" "#6CCE59" "#B4DD2C" "#FDE725"
> scales::col_numeric(viridisLite::viridis(10), domain = df$x)(df$x)
 [1] "#440154" "#482878" "#3E4A89" "#31688E" "#26828E" "#1F9E89" "#35B779" "#6DCD59" "#B4DE2C" "#FDE725"
```
Though I am not sure there is a clear "correct" here.

**Comment by SymbolixAU** [comment]
I think there will be a bit of noise due to the interpolation function. I'm using [boost's cubic_b_spline](https://github.com/SymbolixAU/RcppViridis/blob/master/inst/include/RcppViridis/colours/colours.hpp#L15), for no other reason than boost is awesome. And I haven't looked into what `scales` uses.

**Comment by tim-salabim** [comment]
Good point. As I said there is no clear correct way here...
